CREATE TABLE IF NOT EXISTS "lead_row" (
	-- внутренний ключ
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
	-- сквозной id наружу (Скорозвон external_id). Пишет API
	"uuid" VARCHAR NOT NULL UNIQUE,
	-- нормализованный E.164. Сырой в outbox, Worker нормализует
	"phone" VARCHAR NOT NULL,
	-- false = битый, в обзвон не идёт. Пишет Worker
	"phone_valid" BOOLEAN NOT NULL DEFAULT false,
	-- родительский источник от токена. Пишет Worker
	"source_id" INT,
	-- под-источник после дробления. Пишет Worker. Nullable
	"child_source_id" INT,
	-- результат каскада. Nullable
	"region_id" INT,
	-- 1=от поставщика / 2=Росреестр / 3=оператор / 0=не определён
	"region_source" SMALLINT,
	-- город клиента из анкеты оператора. Nullable
	"city" VARCHAR,
	-- снимок оператора на момент обработки. Nullable
	"operator_id" INT,
	-- 1=от поставщика / 2=определён по номеру / 0=не определён
	"operator_source" SMALLINT,
	-- id строки у поставщика. Ключ идемпотентности приёма. Nullable
	"web_id" VARCHAR,
	-- тег строки. Nullable
	"tag" VARCHAR,
	-- id результата сценария Скорозвона. Nullable
	"call_result" SMALLINT,
	-- id звонка в Скорозвоне. Nullable
	"call_id" VARCHAR,
	-- ссылка на запись разговора. Nullable
	"call_url" VARCHAR,
	-- время последнего звонка. Nullable
	"call_last_at" TIMESTAMP,
	-- id проекта Скорозвона. Nullable
	"project_num" VARCHAR,
	-- jsonb: ответы анкеты оператора. Ключи: imya summa_dolga vid_dolga dohod zalog imuschestvo bankrotstvo gorod. Nullable
	"call_form" VARCHAR,
	-- 1=принята 2=обогащена 3=в СК 4=из СК 5=в Б24 6=отклонена 7=ожидание
	"status_id" SMALLINT NOT NULL,
	-- ключ объекта в S3. NOT NULL — S3 всегда пишется до Postgres. NULL только для мигрированных исторических строк
	"s3_key" VARCHAR NOT NULL,
	-- дата архивации. NULL = активная строка. NOT NULL = в архиве S3
	"archived_at" TIMESTAMP,
	-- время приёма. Пишет API
	"created_at" TIMESTAMP NOT NULL,
	-- время последнего обновления. Nullable
	"updated_at" TIMESTAMP,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "lead_row" IS 'Три писателя: API (приём + s3_key), Worker (обогащение), API-webhook (call_* + call_form от Скорозвона). Индексы: phone, web_id, source_id+created_at, status_id, archived_at';
COMMENT ON COLUMN "lead_row"."id" IS 'внутренний ключ';
COMMENT ON COLUMN "lead_row"."uuid" IS 'сквозной id наружу (Скорозвон external_id). Пишет API';
COMMENT ON COLUMN "lead_row"."phone" IS 'нормализованный E.164. Сырой в outbox, Worker нормализует';
COMMENT ON COLUMN "lead_row"."phone_valid" IS 'false = битый, в обзвон не идёт. Пишет Worker';
COMMENT ON COLUMN "lead_row"."source_id" IS 'родительский источник от токена. Пишет Worker';
COMMENT ON COLUMN "lead_row"."child_source_id" IS 'под-источник после дробления. Пишет Worker. Nullable';
COMMENT ON COLUMN "lead_row"."region_id" IS 'результат каскада. Nullable';
COMMENT ON COLUMN "lead_row"."region_source" IS '1=от поставщика / 2=Росреестр / 3=оператор / 0=не определён';
COMMENT ON COLUMN "lead_row"."city" IS 'город клиента из анкеты оператора. Nullable';
COMMENT ON COLUMN "lead_row"."operator_id" IS 'снимок оператора на момент обработки. Nullable';
COMMENT ON COLUMN "lead_row"."operator_source" IS '1=от поставщика / 2=определён по номеру / 0=не определён';
COMMENT ON COLUMN "lead_row"."web_id" IS 'id строки у поставщика. Ключ идемпотентности приёма. Nullable';
COMMENT ON COLUMN "lead_row"."tag" IS 'тег строки. Nullable';
COMMENT ON COLUMN "lead_row"."call_result" IS 'id результата сценария Скорозвона. Nullable';
COMMENT ON COLUMN "lead_row"."call_id" IS 'id звонка в Скорозвоне. Nullable';
COMMENT ON COLUMN "lead_row"."call_url" IS 'ссылка на запись разговора. Nullable';
COMMENT ON COLUMN "lead_row"."call_last_at" IS 'время последнего звонка. Nullable';
COMMENT ON COLUMN "lead_row"."project_num" IS 'id проекта Скорозвона. Nullable';
COMMENT ON COLUMN "lead_row"."call_form" IS 'jsonb: ответы анкеты оператора. Ключи: imya summa_dolga vid_dolga dohod zalog imuschestvo bankrotstvo gorod. Nullable';
COMMENT ON COLUMN "lead_row"."status_id" IS '1=принята 2=обогащена 3=в СК 4=из СК 5=в Б24 6=отклонена 7=ожидание';
COMMENT ON COLUMN "lead_row"."s3_key" IS 'ключ объекта в S3. NOT NULL — S3 всегда пишется до Postgres. NULL только для мигрированных исторических строк';
COMMENT ON COLUMN "lead_row"."archived_at" IS 'дата архивации. NULL = активная строка. NOT NULL = в архиве S3';
COMMENT ON COLUMN "lead_row"."created_at" IS 'время приёма. Пишет API';
COMMENT ON COLUMN "lead_row"."updated_at" IS 'время последнего обновления. Nullable';

CREATE TABLE IF NOT EXISTS "dispatch" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
	"lead_row_id" BIGINT NOT NULL,
	"channel_id" SMALLINT NOT NULL,
	-- nullable — только для channel=вебхук-партнёр
	"upk_id" INT,
	-- nullable — только для channel=Скорозвон
	"skorozvon_project_id" VARCHAR,
	"sent_at" TIMESTAMP NOT NULL,
	"sent_ok" BOOLEAN NOT NULL,
	-- id организации в СК или ответ вебхука партнёра. Nullable
	"external_id" VARCHAR,
	"attempts" SMALLINT NOT NULL DEFAULT 1,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "dispatch" IS 'UNIQUE (lead_row_id, channel_id, upk_id). Индексы: (upk_id, sent_at), (sent_at). Пишется только после подтверждения от внешней системы';
COMMENT ON COLUMN "dispatch"."upk_id" IS 'nullable — только для channel=вебхук-партнёр';
COMMENT ON COLUMN "dispatch"."skorozvon_project_id" IS 'nullable — только для channel=Скорозвон';
COMMENT ON COLUMN "dispatch"."external_id" IS 'id организации в СК или ответ вебхука партнёра. Nullable';

CREATE TABLE IF NOT EXISTS "event" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
	"lead_row_id" BIGINT NOT NULL,
	"event_type_id" SMALLINT NOT NULL,
	"occurred_at" TIMESTAMP NOT NULL,
	-- 1=Worker / 2=Скорозвон / 3=API / 4=внешнее
	"source" SMALLINT NOT NULL,
	-- причина отклонения, комментарий. Nullable
	"details" VARCHAR,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "event" IS 'APPEND ONLY — только INSERT, никаких UPDATE/DELETE. Индексы: (lead_row_id, occurred_at), (event_type_id, occurred_at)';
COMMENT ON COLUMN "event"."source" IS '1=Worker / 2=Скорозвон / 3=API / 4=внешнее';
COMMENT ON COLUMN "event"."details" IS 'причина отклонения, комментарий. Nullable';

CREATE TABLE IF NOT EXISTS "dedup_result" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
	"lead_row_id" BIGINT NOT NULL,
	"provider_id" INT NOT NULL,
	"value_id" SMALLINT NOT NULL,
	"checked_at" TIMESTAMP NOT NULL,
	-- сырой ответ провайдера. Nullable
	"raw_response" VARCHAR,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "dedup_result" IS 'Актуальный результат = последняя запись по (lead_row_id, provider_id, checked_at DESC)';
COMMENT ON COLUMN "dedup_result"."raw_response" IS 'сырой ответ провайдера. Nullable';

CREATE TABLE IF NOT EXISTS "outbox" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
	"lead_row_id" BIGINT NOT NULL,
	-- источник строки — Worker читает отсюда без обращения к lead_row
	"source_id" INT NOT NULL,
	-- сырые данные для Worker: телефон, регион, оператор от поставщика
	"payload" VARCHAR NOT NULL,
	"created_at" TIMESTAMP NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "outbox" IS 'Worker читает напрямую через SELECT SKIP LOCKED — без Rabbit. Удаление после обработки. Самоочищается';
COMMENT ON COLUMN "outbox"."source_id" IS 'источник строки — Worker читает отсюда без обращения к lead_row';
COMMENT ON COLUMN "outbox"."payload" IS 'сырые данные для Worker: телефон, регион, оператор от поставщика';

CREATE TABLE IF NOT EXISTS "source" (
	"id" INT GENERATED BY DEFAULT AS IDENTITY,
	-- NULL = корневой поставщик. Заполнен = под-источник (наш внутренний id, не из Bitrix)
	"parent_id" INT,
	"name" VARCHAR NOT NULL,
	-- код UC_* или числовой id из Bitrix. Для маппинга при миграции. Nullable
	"bitrix_code" VARCHAR,
	-- токен хука для приёма. Только у корневых. Хранится в открытом виде. Nullable
	"token" VARCHAR,
	-- метка холодной базы. Nullable
	"cold_label" VARCHAR,
	-- метка какой базы. Nullable
	"base_label" VARCHAR,
	-- false = приём остановлен (403 Forbidden)
	"is_active" BOOLEAN NOT NULL DEFAULT true,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "source" IS 'Self-reference: parent_id ссылается на id этой же таблицы. При миграции: сначала корневые (parent_id=NULL), потом под-источники';
COMMENT ON COLUMN "source"."parent_id" IS 'NULL = корневой поставщик. Заполнен = под-источник (наш внутренний id, не из Bitrix)';
COMMENT ON COLUMN "source"."bitrix_code" IS 'код UC_* или числовой id из Bitrix. Для маппинга при миграции. Nullable';
COMMENT ON COLUMN "source"."token" IS 'токен хука для приёма. Только у корневых. Хранится в открытом виде. Nullable';
COMMENT ON COLUMN "source"."cold_label" IS 'метка холодной базы. Nullable';
COMMENT ON COLUMN "source"."base_label" IS 'метка какой базы. Nullable';
COMMENT ON COLUMN "source"."is_active" IS 'false = приём остановлен (403 Forbidden)';

CREATE TABLE IF NOT EXISTS "source_split" (
	"id" INT GENERATED BY DEFAULT AS IDENTITY,
	-- родительский источник
	"source_id" INT NOT NULL,
	"operator_id" INT NOT NULL,
	-- результирующий под-источник
	"child_source_id" INT NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "source_split" IS 'UNIQUE (source_id, operator_id). Одно правило на пару (источник + оператор). Несколько операторов = несколько строк';
COMMENT ON COLUMN "source_split"."source_id" IS 'родительский источник';
COMMENT ON COLUMN "source_split"."child_source_id" IS 'результирующий под-источник';

CREATE TABLE IF NOT EXISTS "source_upk" (
	"source_id" INT NOT NULL,
	"upk_id" INT NOT NULL,
	-- true = можно продавать / false = стоп-лист
	"allowed" BOOLEAN NOT NULL
);

COMMENT ON COLUMN "source_upk"."allowed" IS 'true = можно продавать / false = стоп-лист';

CREATE TABLE IF NOT EXISTS "source_skorozvon" (
	"id" INT GENERATED BY DEFAULT AS IDENTITY,
	"source_id" INT NOT NULL,
	-- id проекта в Скорозвоне (call_project_id)
	"project_id" VARCHAR NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "source_skorozvon"."project_id" IS 'id проекта в Скорозвоне (call_project_id)';

CREATE TABLE IF NOT EXISTS "upk" (
	"id" INT GENERATED BY DEFAULT AS IDENTITY,
	-- РТ / КР / ББ / ...
	"name" VARCHAR NOT NULL,
	"webhook_url" VARCHAR NOT NULL,
	-- период дедупа по номеру в днях. NULL = без ограничений
	"dedup_days" SMALLINT,
	"is_active" BOOLEAN NOT NULL DEFAULT true,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "upk"."name" IS 'РТ / КР / ББ / ...';
COMMENT ON COLUMN "upk"."dedup_days" IS 'период дедупа по номеру в днях. NULL = без ограничений';

CREATE TABLE IF NOT EXISTS "region" (
	"id" INT GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR NOT NULL,
	-- ОКТМО или внешний код. Nullable
	"code" VARCHAR,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "region"."code" IS 'ОКТМО или внешний код. Nullable';

CREATE TABLE IF NOT EXISTS "operator" (
	"id" INT GENERATED BY DEFAULT AS IDENTITY,
	-- БИЛАЙН / МТС / МЕГАФОН / ТЕЛЕ-2 / ДРУГИЕ
	"name" VARCHAR NOT NULL,
	-- оригинальное название из Bitrix для маппинга при миграции. Nullable
	"bitrix_name" VARCHAR,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "operator"."name" IS 'БИЛАЙН / МТС / МЕГАФОН / ТЕЛЕ-2 / ДРУГИЕ';
COMMENT ON COLUMN "operator"."bitrix_name" IS 'оригинальное название из Bitrix для маппинга при миграции. Nullable';

CREATE TABLE IF NOT EXISTS "status" (
	"id" SMALLINT,
	"name" VARCHAR NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "status" IS '1=принята 2=обогащена 3=в СК 4=из СК 5=в Б24 6=отклонена 7=ожидание';

CREATE TABLE IF NOT EXISTS "channel" (
	"id" SMALLINT,
	"name" VARCHAR NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "channel" IS '1=Скорозвон 2=вебхук-партнёр 3=Битрикс';

CREATE TABLE IF NOT EXISTS "event_type" (
	"id" SMALLINT,
	"name" VARCHAR NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "event_type" IS '1=принята 2=обогащена 3=в СК 4=из СК 5=партнёру 6=в Б24 7=отклонена 8=архивирована';

CREATE TABLE IF NOT EXISTS "dedup_provider" (
	"id" INT GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR NOT NULL,
	"is_active" BOOLEAN NOT NULL DEFAULT true,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "dedup_value" (
	"id" SMALLINT,
	"provider_id" INT NOT NULL,
	-- Заря v1 (старый): Чистый/ДЮ/ДС<90/ДС>90/Ошибка. Заря v2 (новый): true/false — уточнить у Вовы
	"name" VARCHAR NOT NULL,
	PRIMARY KEY("id")
);

COMMENT ON COLUMN "dedup_value"."name" IS 'Заря v1 (старый): Чистый/ДЮ/ДС<90/ДС>90/Ошибка. Заря v2 (новый): true/false — уточнить у Вовы';

ALTER TABLE "lead_row"
ADD FOREIGN KEY("source_id") REFERENCES "source"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "lead_row"
ADD FOREIGN KEY("child_source_id") REFERENCES "source"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "lead_row"
ADD FOREIGN KEY("region_id") REFERENCES "region"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "lead_row"
ADD FOREIGN KEY("operator_id") REFERENCES "operator"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "lead_row"
ADD FOREIGN KEY("status_id") REFERENCES "status"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dispatch"
ADD FOREIGN KEY("lead_row_id") REFERENCES "lead_row"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dispatch"
ADD FOREIGN KEY("channel_id") REFERENCES "channel"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dispatch"
ADD FOREIGN KEY("upk_id") REFERENCES "upk"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "event"
ADD FOREIGN KEY("lead_row_id") REFERENCES "lead_row"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "event"
ADD FOREIGN KEY("event_type_id") REFERENCES "event_type"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dedup_result"
ADD FOREIGN KEY("lead_row_id") REFERENCES "lead_row"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dedup_result"
ADD FOREIGN KEY("provider_id") REFERENCES "dedup_provider"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dedup_result"
ADD FOREIGN KEY("value_id") REFERENCES "dedup_value"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "outbox"
ADD FOREIGN KEY("lead_row_id") REFERENCES "lead_row"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "outbox"
ADD FOREIGN KEY("source_id") REFERENCES "source"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "source"
ADD FOREIGN KEY("parent_id") REFERENCES "source"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "source_split"
ADD FOREIGN KEY("source_id") REFERENCES "source"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "source_split"
ADD FOREIGN KEY("operator_id") REFERENCES "operator"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "source_split"
ADD FOREIGN KEY("child_source_id") REFERENCES "source"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "source_upk"
ADD FOREIGN KEY("source_id") REFERENCES "source"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "source_upk"
ADD FOREIGN KEY("upk_id") REFERENCES "upk"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "source_skorozvon"
ADD FOREIGN KEY("source_id") REFERENCES "source"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "dedup_value"
ADD FOREIGN KEY("provider_id") REFERENCES "dedup_provider"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
